### ISSUE TITLE
Permission denied with gitlab

### ISSUE THREAD

**Issue by upendrak** [lanagarmire/Granatum#5]
I am trying to setup Granatum on an Ubuntu server and when I tried to run the steps in the `machine_setup.sh`, I am getting this error

```
git clone git@gitlab.com:breckuh/granatum1.git
Cloning into 'granatum1'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you please let me know how to get access to this repo?
Thanks,
Upendra

**Comment by breckuh** [comment]
Hi Upendra,

Sorry about that! We moved this repo from GitLab to GitHub and I did not update that link. If you just swap that link with the github one, that should fix that part (I also updated the code if you pull the latest).

-Breck

**Comment by upendrak** [comment]
Thanks, Breck for fixing the issue quickly.

I will give it a try and let you know how it goes.
